import { ArchitectureReviewContentSchema } from "@/domain/entities/ArchitectureReview";

export const architectureReviewContent = ArchitectureReviewContentSchema.parse({
  title: "Solicitar evaluación de arquitectura",
  intro:
    "Este proceso es para equipos o proyectos con un problema real de rendimiento, escalabilidad, arquitectura o integración técnica que necesita criterio serio antes de ejecutar.",
  whatYouGet: [
    "Lectura preliminar del problema con foco técnico",
    "Diagnóstico inicial de riesgos, cuellos de botella o complejidad innecesaria",
    "Siguiente paso recomendado según contexto y prioridad",
  ],
  fitCriteria: [
    "Startups con producto técnico y necesidad de escalar",
    "Empresas B2B con procesos digitales ineficientes",
    "Creadores o equipos premium que necesitan IA aplicada con criterio operativo",
    "Sistemas con cuellos de botella de rendimiento o arquitectura",
  ],
  nonFitCriteria: [
    "Consultas vagas sin problema definido",
    "Pedidos puramente decorativos sin necesidad técnica real",
    "Solicitudes de soporte informal sin contexto suficiente",
  ],
  responseExpectation:
    "Responderé personalmente por escrito con un análisis técnico preliminar y una propuesta de pasos a seguir en un plazo máximo de 48 horas hábiles.",
  submitLabel: "Enviar evaluación",
  fields: [
    {
      name: "name",
      label: "Nombre",
      type: "text",
      required: true,
      placeholder: "Tu nombre",
    },
    {
      name: "email",
      label: "Email",
      type: "email",
      required: true,
      placeholder: "tu@email.com",
    },
    {
      name: "companyOrProject",
      label: "Empresa o proyecto",
      type: "text",
      required: true,
      placeholder: "Nombre de la empresa, producto o iniciativa",
    },
    {
      name: "productType",
      label: "Tipo de producto",
      type: "text",
      required: true,
      placeholder: "SaaS, plataforma interna, producto de contenido, e-commerce, etc.",
    },
    {
      name: "problemDescription",
      label: "Descripción del problema",
      type: "textarea",
      required: true,
      placeholder: "Describe el problema principal con el mayor contexto posible",
    },
    {
      name: "currentSystemState",
      label: "Estado actual del sistema",
      type: "textarea",
      required: true,
      placeholder: "¿Qué existe hoy y qué está fallando o limitando?",
    },
    {
      name: "primaryPainPoint",
      label: "Pain point principal",
      type: "text",
      required: true,
      placeholder: "Rendimiento, costos, escalabilidad, automatización, deuda técnica, etc.",
    },
    {
      name: "urgency",
      label: "Urgencia",
      type: "select",
      required: true,
      options: ["low", "medium", "high", "critical"],
      helpText: "Selecciona la prioridad actual del problema.",
    },
    {
      name: "desiredOutcome",
      label: "Objetivo esperado",
      type: "textarea",
      required: true,
      placeholder: "¿Qué resultado esperas conseguir?",
    },
    {
      name: "currentStack",
      label: "Stack actual",
      type: "text",
      required: false,
      placeholder: "Next.js, Node, Python, Rust, Supabase, etc.",
    },
    {
      name: "estimatedTraffic",
      label: "Volumen estimado de usuarios o tráfico",
      type: "text",
      required: false,
      placeholder: "Ej: 10k MAU, 500 requests/min, 50 operadores internos",
    },
    {
      name: "technicalConstraints",
      label: "Restricciones técnicas",
      type: "textarea",
      required: false,
      placeholder: "Compliance, infraestructura heredada, costos, equipo, integraciones, etc.",
    },
    {
      name: "relevantLinks",
      label: "Links relevantes",
      type: "url",
      required: false,
      placeholder: "https://...",
    },
    {
      name: "timeline",
      label: "Plazo estimado",
      type: "text",
      required: false,
      placeholder: "Ej: este trimestre, dentro de 6 semanas, ASAP",
    },
    {
      name: "budgetRange",
      label: "Rango de presupuesto (opcional)",
      type: "text",
      required: false,
      placeholder: "Opcional, si ya existe un rango definido",
    },
  ],
});
