import { ArchitectureReviewContentSchema } from "@/domain/entities/ArchitectureReview";

export const architectureReviewContentEn = ArchitectureReviewContentSchema.parse({
  title: "Request architecture evaluation",
  intro:
    "This process is for teams or projects with a real performance, scalability, architecture, or technical integration issue that needs serious judgment before execution.",
  whatYouGet: [
    "Preliminary reading of the problem with a technical focus",
    "Initial diagnosis of risks, bottlenecks, or unnecessary complexity",
    "Recommended next step based on context and priority",
  ],
  fitCriteria: [
    "Startups with a technical product and a need to scale",
    "B2B companies with inefficient digital processes",
    "Premium creators or teams who need AI applied with operational criteria",
    "Systems with performance or architectural bottlenecks",
  ],
  nonFitCriteria: [
    "Vague inquiries without a defined problem",
    "Purely decorative requests without a real technical need",
    "Informal support requests without sufficient context",
  ],
  responseExpectation:
    "I will personally reply in writing with a preliminary technical analysis and a proposed next step within a maximum of 48 business hours.",
  submitLabel: "Submit evaluation",
  fields: [
    {
      name: "name",
      label: "Name",
      type: "text",
      required: true,
      placeholder: "Your name",
    },
    {
      name: "email",
      label: "Email",
      type: "email",
      required: true,
      placeholder: "you@email.com",
    },
    {
      name: "companyOrProject",
      label: "Company or project",
      type: "text",
      required: true,
      placeholder: "Name of the company, product, or initiative",
    },
    {
      name: "productType",
      label: "Product type",
      type: "text",
      required: true,
      placeholder: "SaaS, internal platform, content product, e-commerce, etc.",
    },
    {
      name: "problemDescription",
      label: "Description of the problem",
      type: "textarea",
      required: true,
      placeholder: "Describe the main problem with as much context as possible",
    },
    {
      name: "currentSystemState",
      label: "Current state of the system",
      type: "textarea",
      required: true,
      placeholder: "What exists today and what is failing or limiting?",
    },
    {
      name: "primaryPainPoint",
      label: "Primary pain point",
      type: "text",
      required: true,
      placeholder: "Performance, costs, scalability, automation, technical debt, etc.",
    },
    {
      name: "urgency",
      label: "Urgency",
      type: "select",
      required: true,
      options: ["low", "medium", "high", "critical"],
      helpText: "Select the current priority of the problem.",
    },
    {
      name: "desiredOutcome",
      label: "Desired outcome",
      type: "textarea",
      required: true,
      placeholder: "What result do you expect to achieve?",
    },
    {
      name: "currentStack",
      label: "Current stack",
      type: "text",
      required: false,
      placeholder: "Next.js, Node, Python, Rust, Supabase, etc.",
    },
    {
      name: "estimatedTraffic",
      label: "Estimated user volume or traffic",
      type: "text",
      required: false,
      placeholder: "E.g., 10k MAU, 500 requests/min, 50 internal operators",
    },
    {
      name: "technicalConstraints",
      label: "Technical constraints",
      type: "textarea",
      required: false,
      placeholder: "Compliance, legacy infrastructure, costs, team, integrations, etc.",
    },
    {
      name: "relevantLinks",
      label: "Relevant links",
      type: "url",
      required: false,
      placeholder: "https://...",
    },
    {
      name: "timeline",
      label: "Estimated timeline",
      type: "text",
      required: false,
      placeholder: "E.g., this quarter, within 6 weeks, ASAP",
    },
    {
      name: "budgetRange",
      label: "Budget range (optional)",
      type: "text",
      required: false,
      placeholder: "Optional, if a range is already defined",
    },
  ],
});
